/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import Pesquisar.JDlgUsuariosPesquisar;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author user
 */
public class JDlgUsuarios_mgar extends javax.swing.JDialog {
    private MaskFormatter mascaraCpf, mascaraData;    
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuarios_mgar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Usuarios");
        
        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir,jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar, jFmtDataNasc_mgar);
        
        Util.habilitar(true,  jBtnAlterar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir);
        
        Util.limpar(jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
 
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios_mgar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpf_mgar.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmtDataNasc_mgar.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnConfirmar = new javax.swing.JButton();
        jLbSenha = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jPwdSenha_mgar = new javax.swing.JPasswordField();
        jBtnPesquisar = new javax.swing.JButton();
        jLbNivel = new javax.swing.JLabel();
        jLbCodigo = new javax.swing.JLabel();
        jCboNivel_mgar = new javax.swing.JComboBox<>();
        jTxtCodigo_mgar = new javax.swing.JTextField();
        jLbDataNasc = new javax.swing.JLabel();
        jLbNome = new javax.swing.JLabel();
        jFmtDataNasc_mgar = new javax.swing.JFormattedTextField();
        jTxtNome_mgar = new javax.swing.JTextField();
        jChbAtivo_mgar = new javax.swing.JCheckBox();
        jLbApelido = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jTxtApelido_mgar = new javax.swing.JTextField();
        jBtnAlterar = new javax.swing.JButton();
        jLbCpf = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jFmtCpf_mgar = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLbSenha.setText("Senha:");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jPwdSenha_mgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwdSenha_mgarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLbNivel.setText("Nível:");

        jLbCodigo.setText("Código:");

        jCboNivel_mgar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cliente", "Funcionario" }));

        jTxtCodigo_mgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigo_mgarActionPerformed(evt);
            }
        });

        jLbDataNasc.setText("Data de Nascimento:");

        jLbNome.setText("Nome:");

        jFmtDataNasc_mgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNasc_mgarActionPerformed(evt);
            }
        });

        jChbAtivo_mgar.setText("Ativo");
        jChbAtivo_mgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivo_mgarActionPerformed(evt);
            }
        });

        jLbApelido.setText("Apelido:");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jLbCpf.setText("Cpf:");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jFmtCpf_mgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpf_mgarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbCodigo)
                                    .addComponent(jLbNome)
                                    .addComponent(jLbApelido)
                                    .addComponent(jLbCpf)
                                    .addComponent(jTxtCodigo_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbSenha)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPwdSenha_mgar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(jFmtCpf_mgar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbNivel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jCboNivel_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(132, 132, 132)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jChbAtivo_mgar)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jFmtDataNasc_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLbDataNasc)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtApelido_mgar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                    .addComponent(jTxtNome_mgar, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLbCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbApelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApelido_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCpf)
                    .addComponent(jLbDataNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtCpf_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataNasc_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPwdSenha_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbAtivo_mgar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboNivel_mgar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir,jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
       
        Util.habilitar(true,  jBtnAlterar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir);
        
        Util.limpar(jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
        
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:]
             // TODO add your handling code here:
        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir,jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
       
        Util.habilitar(true,  jBtnAlterar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir);
        
        Util.limpar(jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
       
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jPwdSenha_mgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwdSenha_mgarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwdSenha_mgarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgUsuariosPesquisar jDlgUsuariosPesquisar = new JDlgUsuariosPesquisar(null, true);
        jDlgUsuariosPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jTxtCodigo_mgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigo_mgarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtCodigo_mgarActionPerformed

    private void jFmtDataNasc_mgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNasc_mgarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNasc_mgarActionPerformed

    private void jChbAtivo_mgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivo_mgarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivo_mgarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:
        Util.habilitar(true, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir,jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
       
        Util.habilitar(false,  jBtnAlterar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir);
        
        Util.limpar(jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
        
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir,jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
       
        Util.habilitar(false,  jBtnAlterar, jBtnExcluir, jBtnPesquisar,
                jBtnIncluir);
        
        Util.limpar(jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
         int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir?",
                "Deletar Registro", JOptionPane.YES_NO_OPTION);
        
       if (resp == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Exclusão realizada.");
            Util.limpar(jTxtCodigo_mgar,jTxtNome_mgar,jTxtApelido_mgar,jFmtCpf_mgar,jPwdSenha_mgar,
                jCboNivel_mgar,jChbAtivo_mgar,jFmtDataNasc_mgar);
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada");
        }
               
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jFmtCpf_mgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpf_mgarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jFmtCpf_mgarActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_mgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_mgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_mgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios_mgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios_mgar dialog = new JDlgUsuarios_mgar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboNivel_mgar;
    private javax.swing.JCheckBox jChbAtivo_mgar;
    private javax.swing.JFormattedTextField jFmtCpf_mgar;
    private javax.swing.JFormattedTextField jFmtDataNasc_mgar;
    private javax.swing.JLabel jLbApelido;
    private javax.swing.JLabel jLbCodigo;
    private javax.swing.JLabel jLbCpf;
    private javax.swing.JLabel jLbDataNasc;
    private javax.swing.JLabel jLbNivel;
    private javax.swing.JLabel jLbNome;
    private javax.swing.JLabel jLbSenha;
    private javax.swing.JPasswordField jPwdSenha_mgar;
    private javax.swing.JTextField jTxtApelido_mgar;
    private javax.swing.JTextField jTxtCodigo_mgar;
    private javax.swing.JTextField jTxtNome_mgar;
    // End of variables declaration//GEN-END:variables
}
